version: '3.8'

services:
  broker:
    build:
      context: .
      dockerfile: Dockerfile.broker
    ports:
      - "14000:14000"

  fragment_manager_1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./fragments:/app/fragments

  fragment_manager_2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5001"
    volumes:
      - ./fragments:/app/fragments

  subscriber:
    build:
      context: .
      dockerfile: Dockerfile.subscriber
    stdin_open: true
    tty: true